[project]
name = "advancedhpc2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chau Nguyen", email = "npc3036@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numba>=0.67.0",
    "numpy>=2.5.3",
    "numba-cuda",
    "pynvjitlink"

]

[tool.uv]
package = false 